import type { DocumentVaultItem } from "./types";

// Placeholder data until a real Document Vault API exists — see
// useDocumentVault.ts for the single seam that will need to change.
export const MOCK_DOCUMENTS: DocumentVaultItem[] = [
  {
    id: "doc-1",
    documentName: "Offer Letter - Bachelor of Computer Science.pdf",
    category: "Offer Letter",
    uploadedBy: "College",
    uploadedAt: "2026-04-02T09:15:00.000Z",
    fileType: "PDF",
    fileSize: "842 KB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-2",
    documentName: "Admission Letter.pdf",
    category: "Admission Letter",
    uploadedBy: "College",
    uploadedAt: "2026-04-05T11:30:00.000Z",
    fileType: "PDF",
    fileSize: "512 KB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-3",
    documentName: "Acceptance Agreement - Signed.pdf",
    category: "Acceptance Agreement",
    uploadedBy: "Student",
    uploadedAt: "2026-04-08T14:00:00.000Z",
    fileType: "PDF",
    fileSize: "1.1 MB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-4",
    documentName: "Tuition Fee Structure 2026.pdf",
    category: "Tuition Fee Structure",
    uploadedBy: "College",
    uploadedAt: "2026-04-10T08:45:00.000Z",
    fileType: "PDF",
    fileSize: "356 KB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-5",
    documentName: "Student ID Card.jpg",
    category: "Student ID Letter",
    uploadedBy: "College",
    uploadedAt: "2026-04-12T10:20:00.000Z",
    fileType: "IMAGE",
    fileSize: "2.3 MB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-6",
    documentName: "Merit Scholarship Award Letter.pdf",
    category: "Scholarship Letter",
    uploadedBy: "College",
    uploadedAt: "2026-04-15T13:10:00.000Z",
    fileType: "PDF",
    fileSize: "298 KB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-7",
    documentName: "Sanction Letter - Unnati Education Loan.pdf",
    category: "Sanction Letter",
    uploadedBy: "Credit Manager",
    uploadedAt: "2026-05-02T09:00:00.000Z",
    fileType: "PDF",
    fileSize: "674 KB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-8",
    documentName: "Loan Agreement - Executed Copy.pdf",
    category: "Loan Agreement",
    uploadedBy: "Credit Manager",
    uploadedAt: "2026-05-06T15:40:00.000Z",
    fileType: "PDF",
    fileSize: "1.4 MB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-9",
    documentName: "Enrollment Certificate.pdf",
    category: "Enrollment Certificate",
    uploadedBy: "College",
    uploadedAt: "2026-05-20T12:00:00.000Z",
    fileType: "PDF",
    fileSize: "489 KB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
  {
    id: "doc-10",
    documentName: "Disbursement Letter - Tranche 1.pdf",
    category: "Disbursement Letter",
    uploadedBy: "Credit Manager",
    uploadedAt: "2026-06-01T10:30:00.000Z",
    fileType: "PDF",
    fileSize: "410 KB",
    downloadUrl: null,
    previewUrl: null,
    status: "AVAILABLE",
  },
];
