import type { ApprovalDetail, ApprovalStage } from "./types";

/**
 * Standing in for a future `GET /applications/approval-workflow` (list) and
 * `GET /applications/:id/approval-workflow` (detail) endpoint pair — the backend has
 * no concept yet of the Checker/CICL/credit-scoring desk this page visualizes.
 * Swap `useApprovalApplications`/`useApprovalApplicationDetail` for real RTK Query
 * hooks once that module exists; component call signatures already match.
 */

const stages = (overrides: Partial<Record<"initiator" | "supporter" | "checker" | "approver", Partial<ApprovalStage>>>): ApprovalStage[] => [
  {
    role: "INITIATOR",
    roleLabel: "Initiator",
    actorName: "R. Bohara",
    actorTitle: "RO",
    status: "DONE",
    comment: "Application submitted. Field visit done.",
    decidedAt: "2026-06-24T09:00:00.000Z",
    ...overrides.initiator,
  },
  {
    role: "SUPPORTER",
    roleLabel: "Supporter",
    actorName: "P. Basnyat",
    actorTitle: "Support",
    status: "DONE",
    comment: "Field visit done. Income consistent. Collateral clear. Recommend approval.",
    decidedAt: "2026-06-26T14:32:00.000Z",
    ...overrides.supporter,
  },
  {
    role: "CHECKER",
    roleLabel: "Checker",
    actorName: "You",
    actorTitle: "CRD",
    status: "ACTIVE",
    ...overrides.checker,
  },
  {
    role: "APPROVER",
    roleLabel: "Approver",
    actorName: "CEO",
    actorTitle: "Approver",
    status: "AWAITING",
    ...overrides.approver,
  },
];

export const MOCK_APPROVAL_APPLICATIONS: ApprovalDetail[] = [
  {
    id: "ln-20260624-093727",
    refNo: "LN-20260624-093727",
    borrowerName: "Sharada Sah Godh",
    branch: "Birgunj",
    loanType: "Agriculture",
    amountLabel: "Rs 7.1L",
    grade: "A2",
    stageLabel: "Approved",
    dsgirLabel: "31.3%",
    ltvLabel: "69.4%",
    daysOpen: 5,
    citizenshipNumber: "12-01-73-04521",
    riskGrade: "A2 — Low risk",
    collateral: "Land, Birgunj",
    insuranceStatus: "Attached",
    offerLetterRef: "N/A",
    offerLetterCollege: "N/A",
    offerLetterVerified: true,
    ciclStatus: "Clear",
    stages: stages({
      checker: { status: "DONE", comment: "Field visit done. Income consistent. Forwarded to approver.", decidedAt: "2026-06-28T10:12:00.000Z" },
      approver: { status: "DONE", comment: "Approved within policy limits.", decidedAt: "2026-06-29T09:40:00.000Z" },
    }),
    creditScore: {
      weighted: 41,
      max: 52,
      grade: "A2",
      riskLabel: "Low risk",
      percentage: 78.8,
      parameters: [
        { label: "Credit facility size", value: "Rs 7.1L", weight: 2, score: 2 },
        { label: "DSGIR", value: "31.3% (Below 40%)", weight: 3, score: 3 },
        { label: "CIC bureau score", value: "740 — No adverse", weight: 3, score: 3 },
        { label: "Banking relationship", value: "Sole banking", weight: 1, score: 1 },
        { label: "Source of income", value: "Agriculture — self", weight: 1, score: 1 },
        { label: "Collateral quality", value: "Prime location", weight: 2, score: 2 },
        { label: "Sector risk", value: "Agriculture", weight: 2, score: 2 },
        { label: "Guarantor strength", value: "Net worth >2x loan", weight: 1, score: 1 },
        { label: "Performance history", value: "No defaults", weight: 2, score: 2 },
        { label: "Institution vintage", value: "Existing customer", weight: 1, score: 1 },
      ],
    },
    complianceChecks: [
      { label: "DSGIR within 50% NRB limit", passed: true },
      { label: "LTV within NRB agriculture cap", passed: true },
      { label: "CICL checked — no adverse", passed: true },
      { label: "PEP screening — clear", passed: true },
      { label: "4-eye rule: 4/4 stages complete", passed: true },
      { label: "Insurance attached", passed: true },
      { label: "Agreement documents generated", passed: true },
    ],
    activity: [
      { role: "APPROVER", roleLabel: "Approver", actorName: "CEO", action: "Approved", note: "Approved within policy limits.", timestamp: "2026-06-29T09:40:00.000Z" },
      { role: "CHECKER", roleLabel: "Checker", actorName: "You", action: "Forwarded to approver", note: "Field visit done. Income consistent. Forwarded to approver.", timestamp: "2026-06-28T10:12:00.000Z" },
      { role: "SUPPORTER", roleLabel: "Supporter", actorName: "P. Basnyat", action: "Supported", note: "Field visit done. Income consistent. Collateral clear. Recommend approval.", timestamp: "2026-06-26T14:32:00.000Z" },
      { role: "INITIATOR", roleLabel: "Initiator", actorName: "R. Bohara", action: "Application submitted", note: "Field visit done.", timestamp: "2026-06-24T09:00:00.000Z" },
    ],
  },
  {
    id: "ln-2081-0142",
    refNo: "LN-2081-0142",
    borrowerName: "Ramesh Thapa",
    branch: "Birgunj",
    loanType: "Business",
    amountLabel: "Rs 25L",
    grade: "A3",
    stageLabel: "CICL Hold",
    dsgirLabel: "42.1%",
    ltvLabel: "72.3%",
    daysOpen: 4,
    citizenshipNumber: "12-01-69-11087",
    riskGrade: "A3 — Moderate risk",
    collateral: "Shop premises, Birgunj",
    insuranceStatus: "Pending",
    offerLetterRef: "N/A",
    offerLetterCollege: "N/A",
    offerLetterVerified: false,
    ciclStatus: "Under Review",
    stages: stages({
      checker: { status: "ACTIVE", comment: "CICL flag found on co-borrower — holding pending clarification." },
    }),
    creditScore: {
      weighted: 33,
      max: 52,
      grade: "A3",
      riskLabel: "Moderate risk",
      percentage: 63.5,
      parameters: [
        { label: "Credit facility size", value: "Rs 25L", weight: 2, score: 2 },
        { label: "DSGIR", value: "42.1% (Above 40%)", weight: 3, score: 2 },
        { label: "CIC bureau score", value: "680 — Flag under review", weight: 3, score: 1 },
        { label: "Banking relationship", value: "Multi-banking", weight: 1, score: 1 },
        { label: "Source of income", value: "Business — private", weight: 1, score: 1 },
        { label: "Collateral quality", value: "Commercial location", weight: 2, score: 2 },
        { label: "Sector risk", value: "Trade & business", weight: 2, score: 1 },
        { label: "Guarantor strength", value: "Net worth 1.5x loan", weight: 1, score: 1 },
        { label: "Performance history", value: "1 late payment (cleared)", weight: 2, score: 1 },
        { label: "Institution vintage", value: "Existing customer", weight: 1, score: 1 },
      ],
    },
    complianceChecks: [
      { label: "DSGIR within 50% NRB limit", passed: true },
      { label: "LTV within NRB business cap", passed: true },
      { label: "CICL checked — flag on co-borrower", passed: false },
      { label: "PEP screening — clear", passed: true },
      { label: "4-eye rule: 2/4 stages complete", passed: false },
      { label: "Insurance attached", passed: false },
      { label: "Agreement documents generated", passed: false },
    ],
    activity: [
      { role: "CHECKER", roleLabel: "Checker", actorName: "You", action: "Placed on CICL hold", note: "CICL flag found on co-borrower — holding pending clarification.", timestamp: "2026-06-27T16:05:00.000Z" },
      { role: "SUPPORTER", roleLabel: "Supporter", actorName: "P. Basnyat", action: "Supported", note: "Collateral verified, recommend approval subject to CICL clearance.", timestamp: "2026-06-26T11:20:00.000Z" },
      { role: "INITIATOR", roleLabel: "Initiator", actorName: "R. Bohara", action: "Application submitted", note: "Business site visit completed.", timestamp: "2026-06-25T09:15:00.000Z" },
    ],
  },
  {
    id: "ln-2081-0148",
    refNo: "LN-2081-0148",
    borrowerName: "Sunita Shrestha",
    branch: "Janakpur",
    loanType: "Home",
    amountLabel: "Rs 45L",
    grade: "A1",
    stageLabel: "Checking",
    dsgirLabel: "28.7%",
    ltvLabel: "58.1%",
    daysOpen: 1,
    citizenshipNumber: "1234/5678",
    riskGrade: "A1 — Low risk",
    collateral: "Land, Janakpur",
    insuranceStatus: "Attached",
    offerLetterRef: "AIM/OFFER/2081-082/0041",
    offerLetterCollege: "Ace Institute of Management",
    offerLetterVerified: true,
    ciclStatus: "Clear",
    stages: stages({}),
    creditScore: {
      weighted: 19,
      max: 52,
      grade: "A1",
      riskLabel: "Low risk",
      percentage: 36.5,
      parameters: [
        { label: "Credit facility size", value: "Below Rs 10L", weight: 2, score: 2 },
        { label: "DSGIR", value: "28.7% (Below 40%)", weight: 3, score: 3 },
        { label: "CIC bureau score", value: "720 — No adverse", weight: 3, score: 3 },
        { label: "Banking relationship", value: "Sole banking", weight: 1, score: 1 },
        { label: "Source of income", value: "Salary — private", weight: 1, score: 2 },
        { label: "Collateral quality", value: "Prime location", weight: 2, score: 2 },
        { label: "Sector risk", value: "Residential", weight: 2, score: 2 },
        { label: "Guarantor strength", value: "Net worth >2x loan", weight: 1, score: 1 },
        { label: "Performance history", value: "No defaults", weight: 2, score: 2 },
        { label: "Institution vintage", value: "New customer", weight: 1, score: 2 },
      ],
    },
    complianceChecks: [
      { label: "DSGIR within 50% NRB limit", passed: true },
      { label: "LTV within NRB home loan cap (60%)", passed: true },
      { label: "CICL checked — no adverse", passed: true },
      { label: "PEP screening — clear", passed: true },
      { label: "NRB Rokka — not blacklisted", passed: true },
      { label: "4-eye rule: 2/4 stages complete", passed: true },
      { label: "Insurance attached", passed: true },
      { label: "College offer letter QR verified", passed: true },
      { label: "Agreement documents generated", passed: true },
      { label: "Within Rs 10L NRB digital lending cap: Rs 4.5L (1st tranche)", passed: true },
    ],
    activity: [
      { role: "SUPPORTER", roleLabel: "Supporter", actorName: "P. Basnyat", action: "Supported", note: "Field visit done. Income consistent. Collateral clear. Recommend approval.", timestamp: "2026-06-26T14:32:00.000Z" },
      { role: "SUPPORTER", roleLabel: "Supporter", actorName: "P. Basnyat", action: "Sent back to initiator", note: "Trace map missing. Re-upload and resubmit.", timestamp: "2026-06-25T11:15:00.000Z" },
      { role: "INITIATOR", roleLabel: "Initiator", actorName: "R. Bohara", action: "Resubmitted", note: "Resubmitted with trace map. CICL report attached.", timestamp: "2026-06-25T15:40:00.000Z" },
      { role: "INITIATOR", roleLabel: "Initiator", actorName: "R. Bohara", action: "Application submitted", note: "Field visit done 24 Jun.", timestamp: "2026-06-24T09:00:00.000Z" },
    ],
  },
  {
    id: "ln-2081-0151",
    refNo: "LN-2081-0151",
    borrowerName: "Hari Prasad Yadav",
    branch: "Birgunj",
    loanType: "Agriculture",
    amountLabel: "Rs 12L",
    grade: "A3",
    stageLabel: "Checking",
    dsgirLabel: "38.9%",
    ltvLabel: "61.5%",
    daysOpen: 2,
    citizenshipNumber: "12-01-71-08832",
    riskGrade: "A3 — Moderate risk",
    collateral: "Farmland, Birgunj",
    insuranceStatus: "Attached",
    offerLetterRef: "N/A",
    offerLetterCollege: "N/A",
    offerLetterVerified: true,
    ciclStatus: "Clear",
    stages: stages({}),
    creditScore: {
      weighted: 30,
      max: 52,
      grade: "A3",
      riskLabel: "Moderate risk",
      percentage: 57.7,
      parameters: [
        { label: "Credit facility size", value: "Rs 12L", weight: 2, score: 2 },
        { label: "DSGIR", value: "38.9% (Below 40%)", weight: 3, score: 2 },
        { label: "CIC bureau score", value: "705 — No adverse", weight: 3, score: 2 },
        { label: "Banking relationship", value: "Sole banking", weight: 1, score: 1 },
        { label: "Source of income", value: "Agriculture — self", weight: 1, score: 1 },
        { label: "Collateral quality", value: "Rural location", weight: 2, score: 1 },
        { label: "Sector risk", value: "Agriculture", weight: 2, score: 2 },
        { label: "Guarantor strength", value: "Net worth 1.2x loan", weight: 1, score: 1 },
        { label: "Performance history", value: "No defaults", weight: 2, score: 2 },
        { label: "Institution vintage", value: "Existing customer", weight: 1, score: 1 },
      ],
    },
    complianceChecks: [
      { label: "DSGIR within 50% NRB limit", passed: true },
      { label: "LTV within NRB agriculture cap", passed: true },
      { label: "CICL checked — no adverse", passed: true },
      { label: "PEP screening — clear", passed: true },
      { label: "4-eye rule: 2/4 stages complete", passed: true },
      { label: "Insurance attached", passed: true },
      { label: "Agreement documents generated", passed: false },
    ],
    activity: [
      { role: "SUPPORTER", roleLabel: "Supporter", actorName: "P. Basnyat", action: "Supported", note: "Farmland verified, income consistent with harvest cycle.", timestamp: "2026-06-27T13:10:00.000Z" },
      { role: "INITIATOR", roleLabel: "Initiator", actorName: "R. Bohara", action: "Application submitted", note: "Field visit done.", timestamp: "2026-06-26T09:30:00.000Z" },
    ],
  },
  {
    id: "ln-2081-0154",
    refNo: "LN-2081-0154",
    borrowerName: "Maya Gurung",
    branch: "Hetauda",
    loanType: "SME",
    amountLabel: "Rs 8L",
    grade: "A4",
    stageLabel: "Checking",
    dsgirLabel: "44.8%",
    ltvLabel: "68.2%",
    daysOpen: 2,
    citizenshipNumber: "27-01-75-05643",
    riskGrade: "A4 — Moderate-high risk",
    collateral: "FDR, Hetauda branch",
    insuranceStatus: "Attached",
    offerLetterRef: "N/A",
    offerLetterCollege: "N/A",
    offerLetterVerified: true,
    ciclStatus: "Clear",
    stages: stages({}),
    creditScore: {
      weighted: 27,
      max: 52,
      grade: "A4",
      riskLabel: "Moderate-high risk",
      percentage: 51.9,
      parameters: [
        { label: "Credit facility size", value: "Rs 8L", weight: 2, score: 2 },
        { label: "DSGIR", value: "44.8% (Above 40%)", weight: 3, score: 1 },
        { label: "CIC bureau score", value: "665 — No adverse", weight: 3, score: 2 },
        { label: "Banking relationship", value: "Sole banking", weight: 1, score: 1 },
        { label: "Source of income", value: "SME — private firm", weight: 1, score: 1 },
        { label: "Collateral quality", value: "FDR — fully liquid", weight: 2, score: 2 },
        { label: "Sector risk", value: "Small trade", weight: 2, score: 1 },
        { label: "Guarantor strength", value: "Net worth 1x loan", weight: 1, score: 1 },
        { label: "Performance history", value: "No defaults", weight: 2, score: 2 },
        { label: "Institution vintage", value: "New customer", weight: 1, score: 1 },
      ],
    },
    complianceChecks: [
      { label: "DSGIR within 50% NRB limit", passed: true },
      { label: "LTV within NRB SME cap", passed: true },
      { label: "CICL checked — no adverse", passed: true },
      { label: "PEP screening — clear", passed: true },
      { label: "4-eye rule: 2/4 stages complete", passed: true },
      { label: "Insurance attached", passed: true },
      { label: "Agreement documents generated", passed: false },
    ],
    activity: [
      { role: "SUPPORTER", roleLabel: "Supporter", actorName: "P. Basnyat", action: "Supported", note: "FDR lien confirmed, income steady.", timestamp: "2026-06-27T10:00:00.000Z" },
      { role: "INITIATOR", roleLabel: "Initiator", actorName: "R. Bohara", action: "Application submitted", note: "Field visit done.", timestamp: "2026-06-27T08:45:00.000Z" },
    ],
  },
  {
    id: "ln-2081-0157",
    refNo: "LN-2081-0157",
    borrowerName: "Ram Thapa",
    branch: "Birgunj",
    loanType: "Business",
    amountLabel: "Rs 9.8L",
    grade: "A3",
    stageLabel: "Checking",
    dsgirLabel: "41.2%",
    ltvLabel: "64.1%",
    daysOpen: 1,
    citizenshipNumber: "12-01-72-09215",
    riskGrade: "A3 — Moderate risk",
    collateral: "Shop premises, Birgunj",
    insuranceStatus: "Attached",
    offerLetterRef: "N/A",
    offerLetterCollege: "N/A",
    offerLetterVerified: true,
    ciclStatus: "Clear",
    stages: stages({}),
    creditScore: {
      weighted: 29,
      max: 52,
      grade: "A3",
      riskLabel: "Moderate risk",
      percentage: 55.8,
      parameters: [
        { label: "Credit facility size", value: "Rs 9.8L", weight: 2, score: 2 },
        { label: "DSGIR", value: "41.2% (Above 40%)", weight: 3, score: 2 },
        { label: "CIC bureau score", value: "698 — No adverse", weight: 3, score: 2 },
        { label: "Banking relationship", value: "Sole banking", weight: 1, score: 1 },
        { label: "Source of income", value: "Business — private", weight: 1, score: 1 },
        { label: "Collateral quality", value: "Commercial location", weight: 2, score: 2 },
        { label: "Sector risk", value: "Trade & business", weight: 2, score: 1 },
        { label: "Guarantor strength", value: "Net worth 1.3x loan", weight: 1, score: 1 },
        { label: "Performance history", value: "No defaults", weight: 2, score: 2 },
        { label: "Institution vintage", value: "Existing customer", weight: 1, score: 1 },
      ],
    },
    complianceChecks: [
      { label: "DSGIR within 50% NRB limit", passed: true },
      { label: "LTV within NRB business cap", passed: true },
      { label: "CICL checked — no adverse", passed: true },
      { label: "PEP screening — clear", passed: true },
      { label: "4-eye rule: 2/4 stages complete", passed: true },
      { label: "Insurance attached", passed: true },
      { label: "Agreement documents generated", passed: false },
    ],
    activity: [
      { role: "SUPPORTER", roleLabel: "Supporter", actorName: "P. Basnyat", action: "Supported", note: "Shop premises verified, ledger consistent.", timestamp: "2026-06-28T09:50:00.000Z" },
      { role: "INITIATOR", roleLabel: "Initiator", actorName: "R. Bohara", action: "Application submitted", note: "Field visit done.", timestamp: "2026-06-27T14:20:00.000Z" },
    ],
  },
  {
    id: "ln-2081-0159",
    refNo: "LN-2081-0159",
    borrowerName: "Birgunj Traders",
    branch: "Birgunj",
    loanType: "Working Capital",
    amountLabel: "Rs 1.2Cr",
    grade: "B",
    stageLabel: "Escalated",
    dsgirLabel: "51.2%",
    ltvLabel: "—",
    daysOpen: 0,
    citizenshipNumber: "PAN-609921134",
    riskGrade: "B — Elevated risk",
    collateral: "Inventory hypothecation",
    insuranceStatus: "Pending",
    offerLetterRef: "N/A",
    offerLetterCollege: "N/A",
    offerLetterVerified: false,
    ciclStatus: "Clear",
    stages: stages({
      checker: { status: "DONE", comment: "Exceeds single obligor limit — escalating to senior credit committee.", decidedAt: "2026-06-29T08:30:00.000Z" },
      approver: { status: "ACTIVE" },
    }),
    creditScore: {
      weighted: 25,
      max: 52,
      grade: "B",
      riskLabel: "Elevated risk",
      percentage: 48.1,
      parameters: [
        { label: "Credit facility size", value: "Rs 1.2Cr", weight: 3, score: 1 },
        { label: "DSGIR", value: "51.2% (Above 50%)", weight: 3, score: 1 },
        { label: "CIC bureau score", value: "690 — No adverse", weight: 3, score: 2 },
        { label: "Banking relationship", value: "Multi-banking", weight: 1, score: 1 },
        { label: "Source of income", value: "Wholesale trade", weight: 1, score: 1 },
        { label: "Collateral quality", value: "Inventory — variable value", weight: 2, score: 1 },
        { label: "Sector risk", value: "Wholesale & retail trade", weight: 2, score: 1 },
        { label: "Guarantor strength", value: "Net worth 1x loan", weight: 1, score: 1 },
        { label: "Performance history", value: "No defaults", weight: 2, score: 2 },
        { label: "Institution vintage", value: "Existing customer", weight: 1, score: 1 },
      ],
    },
    complianceChecks: [
      { label: "DSGIR within 50% NRB limit", passed: false },
      { label: "Single obligor limit", passed: false },
      { label: "CICL checked — no adverse", passed: true },
      { label: "PEP screening — clear", passed: true },
      { label: "4-eye rule: 3/4 stages complete", passed: true },
      { label: "Insurance attached", passed: false },
      { label: "Agreement documents generated", passed: false },
    ],
    activity: [
      { role: "CHECKER", roleLabel: "Checker", actorName: "You", action: "Escalated to approver", note: "Exceeds single obligor limit — escalating to senior credit committee.", timestamp: "2026-06-29T08:30:00.000Z" },
      { role: "SUPPORTER", roleLabel: "Supporter", actorName: "P. Basnyat", action: "Supported", note: "Inventory hypothecation verified, ledger reviewed.", timestamp: "2026-06-29T07:10:00.000Z" },
      { role: "INITIATOR", roleLabel: "Initiator", actorName: "R. Bohara", action: "Application submitted", note: "Working capital renewal request.", timestamp: "2026-06-29T06:00:00.000Z" },
    ],
  },
];

export function getMockApprovalApplications(): ApprovalDetail[] {
  return MOCK_APPROVAL_APPLICATIONS;
}

export function getMockApprovalApplicationById(id: string): ApprovalDetail | undefined {
  return MOCK_APPROVAL_APPLICATIONS.find((app) => app.id === id);
}
